version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: najmatoruser
      POSTGRES_PASSWORD: qwertyuiop
      POSTGRES_DB: najmator
      PGDATA: /tmp/pgdata
  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- ./docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
