version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: najmatoruser
      POSTGRES_PASSWORD: qwertyuiop
      POSTGRES_DB: najmator
      PGDATA: /tmp/pgdata
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db